#!/bin/bash

echo "Iniciando codigo bash"

LED3_PATH=/sys/class/leds/beaglebone:green:usr3

function removeTrigger
{
  echo "none" >> "$LED3_PATH/trigger"
}

echo "starting the LEd bash script"

if [ $# -eq 0 ]; then
 echo "There are argument. Usage is:"
 echo -e " bashLED Command \n where command is one of "
 echo -e " on, off, flash or status \n e.g. bashLED on "
 exit 2
fi

echo "The LED command that was passed is: $1 "

if [ "$1" == "on" ]; then
  echo "Turning the led ON"
  removeTrigger
  echo "1" >> "$LED3_PATH/brightness"
elif [ "$1" == "off" ]; then
 echo "Turning the led OFF"
 removeTrigger
 echo "0" >> "$LED3_PATH/brightness"
elif [ "$1" == "flash" ]; then
 echo "Flashing the LED "
 removeTrigger
 echo "timer" >> "$LED3_PATH/trigger"
 echo "50" >> "$LED3_PATH/delay_on"
 echo "50" >> "$LED3_PATH/delay_off"
elif [ "$1" == "status" ]; then
 cat "$LED3_PATH/trigger";
fi
S
echo "End of the LED Bash Script"
